const TRANSITIONS = {
  NEW: ["MO_VALIDATION"],

  MO_PENDING: ["MO_BREAK_OPEN", "CONFIRMATION_PENDING"],

  MO_VALIDATION: ["MO_BREAK_OPEN", "CONFIRMATION_PENDING"],

  MO_BREAK_OPEN: ["MO_VALIDATION", "PENDING_FO_RESPONSE"], // ✅ FIX

  CONFIRMATION_PENDING: [
  "SETTLEMENT_PENDING",
  "CONFIRMATION_BREAK",
  "PENDING_CPTY_RESPONSE",
  "MO_BREAK_OPEN"
],

CONFIRMATION_BREAK: [
  "MO_BREAK_OPEN",
  "PENDING_CPTY_RESPONSE"
],

  SETTLEMENT_PENDING: ["READY_FOR_APPROVAL"],

  READY_FOR_APPROVAL: ["SETTLED", "SETTLEMENT_BREAK"],

  SETTLEMENT_BREAK: ["SETTLED"],

  SETTLED: ["RECON_PENDING"],

  RECON_PENDING: ["RECON_CLEARED", "UNMATCHED_BY_USER"],

  UNMATCHED_BY_USER: ["RECON_PENDING"],

  RECON_CLEARED: ["CLOSED"],

  CLOSED: [],

  // ✅ S2.9.1 ADDITIONS

  PENDING_FO_RESPONSE: ["MO_VALIDATION", "MO_BREAK_OPEN"],

  PENDING_CPTY_RESPONSE: [
    "CONFIRMATION_PENDING",
    "CONFIRMATION_BREAK",
    "SETTLEMENT_PENDING",
    "SETTLEMENT_BREAK"
  ]

};

module.exports = TRANSITIONS;